// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ktL80T67AmAeh_0wxmN0hYEEFMq6aDs',
    appId: '1:636956432386:android:9c9417d83f64a002f06f1b',
    messagingSenderId: '636956432386',
    projectId: 'aliee-wellness',
    storageBucket: 'aliee-wellness.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdGnqiSLhQQg8UlDtZEkHVTtKygBBkMI4',
    appId: '1:636956432386:ios:f37c09d431b27345f06f1b',
    messagingSenderId: '636956432386',
    projectId: 'aliee-wellness',
    storageBucket: 'aliee-wellness.firebasestorage.app',
    iosBundleId: 'com.spektrum.alieewellness',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8RLxkUXA1h6ixOgyH90ei01ZtWp-bPjw',
    appId: '1:636956432386:web:52fcd0dbe6326a6cf06f1b',
    messagingSenderId: '636956432386',
    projectId: 'aliee-wellness',
    authDomain: 'aliee-wellness.firebaseapp.com',
    storageBucket: 'aliee-wellness.firebasestorage.app',
  );
}
